### ISSUE TITLE
Thrustmaster force feedback gt

### ISSUE THREAD

**Issue by survivor182ca** [berarma/oversteer#116] opened 2022-10-01 17:16 UTC
Hi,

I own this wheel and I was wondering if you could add support for that wheel

The wheel is recognized in kernel 5.15 and it does work properly (without force feedback) with qjoypad

https://support.thrustmaster.com/en/product/ffdrw-en/

Im using linuxmint 21 and oversteer doe not recognized my wheel.

Thank in advance.

**Comment by berarma** [comment] 2022-10-01 18:39
Yes, I need the info from the lsusb command.

**Comment by survivor182ca** [comment] 2022-10-03 18:20
Here is my full lsusb output :

Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub - /dev/bus/usb/001/001
**Bus 001 Device 003: ID 06f8:0004 Guillemot Corp. Guillemot Force Feedback Racing Wheel - /dev/input/js0
Bus 001 Device 003: ID 06f8:0004 Guillemot Corp. Guillemot Force Feedback Racing Wheel - /dev/input/event14
Bus 001 Device 003: ID 06f8:0004 Guillemot Corp. Guillemot Force Feedback Racing Wheel - /dev/bus/usb/001/003**
Bus 001 Device 002: ID 0a12:0001 Cambridge Silicon Radio, Ltd Bluetooth Dongle (HCI mode) - /dev/input/event13
Bus 001 Device 002: ID 0a12:0001 Cambridge Silicon Radio, Ltd Bluetooth Dongle (HCI mode) - /dev/hidraw1
Bus 001 Device 002: ID 0a12:0001 Cambridge Silicon Radio, Ltd Bluetooth Dongle (HCI mode) - /dev/bus/usb/001/002
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub - /dev/bus/usb/002/001
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub - /dev/bus/usb/003/001
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub - /dev/bus/usb/004/001



Let me know if you need more information

**Comment by berarma** [comment] 2022-10-04 10:01
I need the max rotation range. I haven't found the information online. It might be 180° since that's what older Thrustmaster wheels did. That is one quarter left and one quarter right. Can you confirm please?

Notice that your wheel, like any other wheel, doesn't need Oversteer to work. It's just an assistant to help you test it and configure settings in case it has any.

**Comment by survivor182ca** [comment] 2022-10-04 15:32
Now, the wheel actuator does not offer any resistance (no force) when I use it.

Just having some resistance even if the force feedback does not work would be a great improvement.

For the rotation I confirm that it is : one quarter left and one quarter right.

**Comment by berarma** [comment] 2022-10-04 20:18
It's added to the master branch. Please, test and report back. Thanks!

**Comment by survivor182ca** [comment] 2022-10-11 17:27
![2022-10-11_13-22](https://user-images.githubusercontent.com/114826301/195158520-25d1dad6-fe22-4ce2-8e1f-431349c4aaa7.png)

I have not test all settings but It does work.

With setting autocenter strength I now have resistance into the wheel (default setting was =0)

Thank a lot.

qjoypad + oversteer : workable experience =)

I will test furthermore in the upcoming days.

**Comment by Svampebob1** [comment] 2022-10-16 14:08
Any news about this?
I've been using this wheel with the following command:
sudo xboxdrv --evdev /dev/input/by-id/usb-Guillemot_Corp._Guillemot_Force_Feedback_Racing_Wheel-event-joystick \
--evdev-absmap ABS_WHEEL=x1,ABS_BRAKE=LT,ABS_GAS=RT,ABS_HAT0X=dpad_x,ABS_HAT0Y=dpad_y \
--evdev-keymap BTN_TOP=tl,BTN_TRIGGER=tr,BTN_TOP2=back,BTN_THUMB=start,BTN_A=x,BTN_BASE3=y,BTN_BASE4=b,BTN_BASE5=a,BTN_BASE=lt,BTN_BASE2=rt,BTN_GEAR_DOWN=lb,BTN_GEAR_UP=rb \
--dpad-as-button --mimic-xpad --debug --verbose --evdev-debug

FFB not working with xboxdrv. I've tried enabling using --force-feedback.

Force feedback is working when using this command:
fftest /dev/input/by-id/usb-Guillemot_Corp._Guillemot_Force_Feedback_Racing_Wheel-event-joystick

Any hope of getting force feedback working? :-)

**Comment by berarma** [comment] 2022-10-24 12:38
> Any news about this? I've been using this wheel with the following command: sudo xboxdrv --evdev /dev/input/by-id/usb-Guillemot_Corp._Guillemot_Force_Feedback_Racing_Wheel-event-joystick --evdev-absmap ABS_WHEEL=x1,ABS_BRAKE=LT,ABS_GAS=RT,ABS_HAT0X=dpad_x,ABS_HAT0Y=dpad_y --evdev-keymap BTN_BASE3=y,BTN_BASE4=x,BTN_BASE5=start,BTN_BASE6=back,BTN_BASE=a,BTN_BASE2=b,BTN_GEAR_DOWN=rb,BTN_GEAR_UP=lb --dpad-as-button --mimic-xpad --debug --verbose --evdev-debug
> 
> FFB not working with xboxdrv. I've tried enabling using variations of --force-feedback, --detach-kernel-driver and more.
> 
> Force feedback is working when using this command: fftest /dev/input/by-id/usb-Guillemot_Corp._Guillemot_Force_Feedback_Racing_Wheel-event-joystick
> 
> Any hope of getting force feedback working? :-)

I don't know how well `xboxdrv` supports wheel devices. If the FFB is working when directly testing the wheel then the problem is using it with `xboxdrv`. You should ask that project.

I'll close this issue since the reports seem to indicate the wheel is working with Oversteer.

**Closed by berarma** 2022-10-24 12:38 UTC
